
name: publish package to npm
on:
  push:
    tags:
    - 'v*'

env:
  REGISTRY: ghcr.io

jobs:
  publish-package-to-npm:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'chase-moskal'
    steps:

    - name: 🛎️ checkout
      uses: actions/checkout@v2

    - name: 🔧 set up node
      uses: actions/setup-node@v2
      with:
        node-version: '17'

    - name: 📦 npm install
      run: npm ci

    - name: 🔨 build
      run: npm run build

    - name: 🚀 npm publish
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
